import { PLATFORMS } from '../config/constants';

export const skinThemes = {
  [PLATFORMS.TIKTOK]: {
    name: 'TikTok',
    backgroundColor: '#000000',
    primaryColor: '#FF0050',
    secondaryColor: '#25F4EE',
    textColor: '#FFFFFF',
    commentBackgroundColor: 'rgba(0, 0, 0, 0.3)',
    viewerCountStyle: {
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      borderRadius: 20,
      paddingHorizontal: 12,
      paddingVertical: 6,
    },
    commentStyle: {
      fontSize: 14,
      fontWeight: '500',
      marginBottom: 8,
      paddingHorizontal: 12,
      paddingVertical: 6,
      backgroundColor: 'rgba(0, 0, 0, 0.3)',
      borderRadius: 12,
      marginHorizontal: 16,
    },
    usernameColor: '#25F4EE',
    heartColor: '#FF0050',
  },
  [PLATFORMS.INSTAGRAM]: {
    name: 'Instagram',
    backgroundColor: '#000000',
    primaryColor: '#E4405F',
    secondaryColor: '#F77737',
    textColor: '#FFFFFF',
    commentBackgroundColor: 'rgba(0, 0, 0, 0.4)',
    viewerCountStyle: {
      backgroundColor: 'rgba(0, 0, 0, 0.6)',
      borderRadius: 15,
      paddingHorizontal: 10,
      paddingVertical: 4,
    },
    commentStyle: {
      fontSize: 13,
      fontWeight: '400',
      marginBottom: 6,
      paddingHorizontal: 10,
      paddingVertical: 4,
      backgroundColor: 'rgba(0, 0, 0, 0.4)',
      borderRadius: 10,
      marginHorizontal: 12,
    },
    usernameColor: '#F77737',
    heartColor: '#E4405F',
  },
  [PLATFORMS.YOUTUBE]: {
    name: 'YouTube',
    backgroundColor: '#0F0F0F',
    primaryColor: '#FF0000',
    secondaryColor: '#FFFFFF',
    textColor: '#FFFFFF',
    commentBackgroundColor: 'rgba(255, 255, 255, 0.1)',
    viewerCountStyle: {
      backgroundColor: 'rgba(255, 0, 0, 0.8)',
      borderRadius: 4,
      paddingHorizontal: 8,
      paddingVertical: 4,
    },
    commentStyle: {
      fontSize: 12,
      fontWeight: '400',
      marginBottom: 4,
      paddingHorizontal: 8,
      paddingVertical: 3,
      backgroundColor: 'rgba(255, 255, 255, 0.1)',
      borderRadius: 4,
      marginHorizontal: 8,
    },
    usernameColor: '#AAAAAA',
    heartColor: '#FF0000',
  },
  [PLATFORMS.SNAPCHAT]: {
    name: 'Snapchat',
    backgroundColor: '#000000',
    primaryColor: '#FFFC00',
    secondaryColor: '#FFFFFF',
    textColor: '#FFFFFF',
    commentBackgroundColor: 'rgba(255, 252, 0, 0.2)',
    viewerCountStyle: {
      backgroundColor: 'rgba(255, 252, 0, 0.9)',
      borderRadius: 25,
      paddingHorizontal: 15,
      paddingVertical: 8,
    },
    commentStyle: {
      fontSize: 14,
      fontWeight: '600',
      marginBottom: 10,
      paddingHorizontal: 14,
      paddingVertical: 8,
      backgroundColor: 'rgba(255, 252, 0, 0.2)',
      borderRadius: 20,
      marginHorizontal: 20,
    },
    usernameColor: '#FFFC00',
    heartColor: '#FFFC00',
  },
  [PLATFORMS.FACEBOOK]: {
    name: 'Facebook',
    backgroundColor: '#18191A',
    primaryColor: '#1877F2',
    secondaryColor: '#42A5F5',
    textColor: '#E4E6EA',
    commentBackgroundColor: 'rgba(24, 25, 26, 0.8)',
    viewerCountStyle: {
      backgroundColor: 'rgba(24, 119, 242, 0.8)',
      borderRadius: 6,
      paddingHorizontal: 10,
      paddingVertical: 6,
    },
    commentStyle: {
      fontSize: 13,
      fontWeight: '400',
      marginBottom: 8,
      paddingHorizontal: 12,
      paddingVertical: 6,
      backgroundColor: 'rgba(24, 25, 26, 0.8)',
      borderRadius: 8,
      marginHorizontal: 16,
    },
    usernameColor: '#42A5F5',
    heartColor: '#1877F2',
  },
};

